import Head from "next/head";
import React, { useState } from "react";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Layout from "@/component/Layout";
import profilePic from "../../public/images/profile/profilePic.png";
import AnimatedText from "@/component/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/component/Icons";
import HireMe from "@/component/HireMe";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import TransitionEffect from "@/component/TransitionEffect";
import meet from "../../public/images/profile/meet.png";
import neon from "../../public/images/profile/neon.jpg";
import Background from "@/component/Background";

export default function Home() {
  const [showContactModal, setShowContactModal] = useState(false);

  const showContactDetails = () => {
    setShowContactModal(true);
  };

  const closeContactModal = () => {
    setShowContactModal(false);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <TransitionEffect></TransitionEffect>
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout classname="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col ">
            <div className="w-1/2 md:w-full">
              <Image
                src={profilePic}
                alt="Rashmi"
                className="w-full h-auto lg:hidden md:inline-block md:w-full"
                priority={true}
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text="Fueling progress with the spark of curiosity."
                classname="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl "
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                Revving up automotive innovation by day, coding the future of
                the web by night. 🚗💻 Embedded engineer in the automotive
                sector with a passion for web development.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center ">
                <a
                  href="/Resume.pdf"
                  className="flex items-center bg-dark text-light p-2.5 px-6
                    rounded-lg text-lg font-semibold hover:bg-light  hover:text-dark 
                    border-2 border-solid border-transparent hover:border-dark
                    dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light
                    hover:dark:border-light md:p-2 md:px-4 md:text-base border border-4 border-solid border-rose-400"
                  download={true}
                >
                  Resume <LinkArrow className={"w-6 ml-1"} />
                </a>
                <button
                  onClick={showContactDetails}
                  className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base cursor-pointer"
                >
                  Contact
                </button>
                {/* <div className="absolute right-8 bottom-8 inline-block w-24 md:hidden"> */}
                <Image src={meet} alt="Codebucks" className="w-36 h-36 p-3" />
                {/* </div> */}
              </div>
            </div>
          </div>
        </Layout>

        <HireMe />
        {/* <div className="absolute right-8 bottom-8 inline-block w-24 h-24 md:hidden">
          <Image src={meet} alt="Codebucks" className="w-full h-full object-cover" />
        </div> */}

        {showContactModal && (
          <div className="fixed top-0 left-0 w-full h-full flex items-center justify-center bg-black bg-opacity-75">
            <div className="bg-white p-4 rounded-lg">
              <p className="text-lg font-medium mb-4">Contact Details</p>
              <p>Email: rashmi.hiremath304@gmail.com</p>
              <p>Contact Number: 9591219026</p>
              {/* Add any other contact details as needed */}
              <button
                onClick={closeContactModal}
                className="mt-4 bg-dark text-light p-2 px-4 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark"
              >
                Close
              </button>
            </div>
          </div>
        )}
      </main>
    </>
  );
}
